# Generated by Django 3.1.5 on 2021-01-24 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0002_comment_discussion'),
    ]

    operations = [
        migrations.AddField(
            model_name='forum',
            name='slug',
            field=models.SlugField(default='default', unique=True),
            preserve_default=False,
        ),
    ]
