# Generated by Django 3.1.5 on 2021-01-24 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0003_forum_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussion',
            name='slug',
            field=models.SlugField(default='default', unique=True),
            preserve_default=False,
        ),
    ]
