# Generated by Django 3.1.5 on 2021-01-24 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0004_discussion_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussion',
            name='slug',
            field=models.SlugField(),
        ),
    ]
